###
GET http://localhost:3000/


###
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "jora@dev.com",
    "password": "password",
    "fullname": "Joe Biden",
    "birthdate": "5/3/2022, 5:18:46 PM"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "mina@dev.com",
    "password": "password"
}